### ISSUE TITLE
In the README

### ISSUE THREAD

**Issue by thesourcerer8** [Swapnil-Dubey25/TCL_programming#3]
The screenshot in the README shows the error message "Please provide the CSV file.", but it does not explain which CSV file should be provided. Please always be precise in warnings and error message, what is required, and give examples where possible. In the GitHub repository, there are 2 different CSV files, and it isn't obvious which one to use. This definitely has to be documented properly in the README, which file should be used, and it would also be helpful is the tool would recognize and provide a helpful error message if the wrong file has been given:
![grafik](https://github.com/Swapnil-Dubey25/TCL_programming/assets/6086693/b495abfc-4480-4427-bcf9-8f3296ec26ec)
Please try your tool with both CSV files and see what happens.
Also the screenshots in the README do not match the output of your script, please update the screenshots in your README with screenshots from your script.

**Comment by Swapnil-Dubey25** [comment]
The screenshot provided in the repo is absolutely correct 
Thanks for highlighting the key point to mention the file which need to be provided in the script
necessary chnages will be made in the repo accordingly.
