### ISSUE TITLE
Shebang is missing

### ISSUE THREAD

**Issue by thesourcerer8** [Swapnil-Dubey25/TCL_programming#4]
The Shebang is missing in the vlsisynth.tcl file:
https://en.wikipedia.org/wiki/Shebang_(Unix)
Without the Shebang, the system uses the default shell "bash" to execute the script since it does not know which language it uses, but this fails completely
![grafik](https://github.com/Swapnil-Dubey25/TCL_programming/assets/6086693/54b158a4-beee-4cf0-8a44-b53f06eb5599)
The first line of a .tcl script needs to be #!/usr/bin/tclsh
![grafik](https://github.com/Swapnil-Dubey25/TCL_programming/assets/6086693/6ac05738-d2ad-412e-9b32-e1b24c56ad4a)

**Comment by Swapnil-Dubey25** [comment]
please check the vlsisynth file such scipt have been already been provided in the shell file( vlsisynth) already present in the repo
